# Site settings
title: Heather Mayes
description: > # this means to ignore newlines until "baseurl:"
  Heather Mayes's website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.hmayes.com" # the base hostname & protocol for your site
github_username: hmayes

# Build settings
markdown: kramdown
